run:
  timeout: 3m
  tests: true

linters:
  enable:
    - staticcheck
    - govet
    - gofmt
    - goimports
    - gosimple
    - unused
    - ineffassign
    - errcheck
    - depguard

linters-settings:
  staticcheck:
    checks: ["all"]
  gofmt:
    simplify: true
  goimports:
    local-prefixes: "app"

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
  # exclude-rules:
  #   - linters: [staticcheck]
  #     text: "SA1019"

