version: "3"

vars:
  PKGS: ./...

tasks:
  tidy:
    cmds:
      - go mod tidy

  fmt:
    cmds:
      - gofmt -w .
    sources:
      - "**/*.go"

  lint:
    desc: Run go vet and gofmt check
    cmds:
      - go vet ./...
      - gofmt -d .

  lint:fix:
    desc: Auto-fix possible issues
    cmds:
      - gofmt -w .

  test:
    cmds:
      - go test -race -coverprofile=coverage.out {{.PKGS}}

  ci:
    desc: format -> lint -> test
    deps: [tidy]
    cmds:
      - task: fmt
      - task: lint
      - task: test

